### ISSUE TITLE
9.2.5 Fix

### ISSUE THREAD

**Issue by Kerberos9** [eTzmNcbkrng/WardrobeTools#11]
The latest patch change the appearance API, this fixes it:

Change line 202-213 to this:

```
				if (appearanceID) then
					for i, sourceID in ipairs(C_TransmogCollection.GetAllAppearanceSources(appearanceID)) do
						if C_TransmogCollection.PlayerHasTransmogItemModifiedAppearance(sourceID) then
							return true
					end
				end
```

Uploading full file for easier replace
[core.lua.txt](https://github.com/eTzmNcbkrng/WardrobeTools/files/8837583/core.lua.txt)

Remove the .txt.

**Comment by eTzmNcbkrng** [comment]
This change does not fix the issue for me, assuming you have have the same issue whereby the addon is correctly suggesting I equip appearances I don't have but isn't suggesting them to be mailed in accordance with my configured recipients.

**Comment by Kerberos9** [comment]
In my case the addon wouldn't work at all, not the mail and not the /ac command, lua errors would pop up
