### ISSUE TITLE
Mailer and Apperance Collector issue since latest prepatch events

### ISSUE THREAD

**Issue by Uggers** [eTzmNcbkrng/WardrobeTools#13]
Apologies I am not entierly sure if anyone is still using this or working on it. I see a couple of updates done this year to the various forks.

Its been mostly working ok, some characters I'm finding the sezz profile isn't reseting and being deleted. but the main issue at the moment is the mailer function isn't working. The error I am getting on log in is;

`46x WardrobeTools/wardrobe/mailer.lua:636: table index is nil
[string "@WardrobeTools/wardrobe/mailer.lua"]:636: in function `InitializeProfile'
[string "@WardrobeTools/wardrobe/mailer.lua"]:650: in function `OnEnable'
[string "@WardrobeTools/sUI.lua"]:260: in function `SetEnabledState'
[string "@WardrobeTools/wardrobe/mailer.lua"]:619: in function `OnInitialize'
[string "@WardrobeTools/sUI.lua"]:409: in function `?'
[string "@WardrobeTools/sUI.lua"]:182: in function <WardrobeTools/sUI.lua:180>

Locals:
self = Frame {
 0 = <userdata>
 debugName = "AppearanceMailer"
 AddDefaultHandlers = <function> defined @WardrobeTools/sUI.lua:297
 DB = <table> {
 }
 ResetSettings = <function> defined @WardrobeTools/sUI.lua:237
 LoadSettings = <function> defined @WardrobeTools/sUI.lua:206
 _RegisterUnitEvent = <function> defined =[C]:-1
 BAG_UPDATE_DELAYED = <function> defined @WardrobeTools/wardrobe/mailer.lua:687
 ADB = <table> {
 }
 MAIL_SUCCESS = <function> defined @WardrobeTools/wardrobe/mailer.lua:907
 RegisterUnitEvent = <function> defined @WardrobeTools/sUI.lua:176
 MAIL_SHOW = <function> defined @WardrobeTools/wardrobe/mailer.lua:693
 MAIL_FAILED = <function> defined @WardrobeTools/wardrobe/mailer.lua:902
 SetEnabledState = <function> defined @WardrobeTools/sUI.lua:255
 ProcessQueue = <function> defined @WardrobeTools/wardrobe/mailer.lua:863
 Debug = <function> defined @WardrobeTools/sUI.lua:28
 QueueMails = <function> defined @WardrobeTools/wardrobe/mailer.lua:749
 RegisterEvent = <function> defined @WardrobeTools/sUI.lua:147
 InitializeProfile = <function> defined @WardrobeTools/wardrobe/mailer.lua:622
 MAIL_CLOSED = <function> defined @WardrobeTools/wardrobe/mailer.lua:699
 queue = <table> {
 }
 CreateModule = <function> defined @WardrobeTools/sUI.lua:324
 OnEnable = <function> defined @WardrobeTools/wardrobe/mailer.lua:649
 OnDisable = <function> defined @WardrobeTools/wardrobe/mailer.lua:671
 OnInitialize = <function> defined @WardrobeTools/wardrobe/mailer.lua:617
 enabledState = true
 Print = <function> defined @WardrobeTools/sUI.lua:247
 _RegisterEvent = <function> defined =[C]:-1
 PrintError = <function> defined @WardrobeTools/sUI.lua:251
}
(*temporary) = <table> {
 2 = <table> {
 }
 sendAllBoEs = false
 4 = <table> {
 }
 includeBoAArmorTokens = false
 TSMenabled = false
}
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "table index is nil"
S = <table> {
 ScanningTooltip = SezzUIScanningTooltip {
 }
 IsBeta = <function> defined @WardrobeTools/sUI.lua:49
 Scale = <function> defined @WardrobeTools/sUI.lua:109
 modules = <table> {
 }
 GetModule = <function> defined @WardrobeTools/sUI.lua:378
 SkinActionButton = <function> defined @WardrobeTools/sUI.lua:28
 myRealm = "Terenas"
 IsItemTradable = <function> defined @WardrobeTools/wardrobe/core.lua:353
 ItemIsValidTransmogrifySource = <function> defined @WardrobeTools/wardrobe/core.lua:245
 PlayerCanEquip = <function> defined @WardrobeTools/wardrobe/core.lua:282
 IsBagItemTradable = <function> defined @WardrobeTools/wardrobe/core.lua:344
 Clone = <function> defined @WardrobeTools/sUI.lua:517
 RegisterSlashCommand = <function> defined @WardrobeTools/sUI.lua:77
 UnregisterSlashCommand = <function> defined @WardrobeTools/sUI.lua:57
 UIParent = SezzUIParent {
 }
 CreateModule = <function> defined @WardrobeTools/sUI.lua:324
 myFactionGroup = "Alliance"
 myLevel = 60
 PlayerHasTransmog = <function> defined @WardrobeTools/wardrobe/core.lua:130
 GetModuleDefaultSettings = <function> defined @WardrobeTools/sUI.lua:370
 myName = "Manda"
 myClass = "WARRIOR"
 dummy = <function> defined @WardrobeTools/sUI.lua:28
}
LE_ITEM_CLASS_ARMOR = nil
LE_ITEM_CLASS_WEAPON = nil
`

**Comment by Uggers** [comment]
Appearance collector too (I hadn't noticed)

1x ...dOns/WardrobeTools/wardrobe/appearance_collector.lua:45: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@WardrobeTools/wardrobe/appearance_collector.lua"]:45: in function <...dOns/WardrobeTools/wardrobe/appearance_collector.lua:42>
[string "@WardrobeTools/wardrobe/appearance_collector.lua"]:105: in function `Update'
[string "@WardrobeTools/wardrobe/appearance_collector.lua"]:267: in function `OnEnable'
[string "@WardrobeTools/sUI.lua"]:260: in function `SetEnabledState'
[string "@WardrobeTools/wardrobe/appearance_collector.lua"]:303: in function `Toggle'
[string "@WardrobeTools/wardrobe/appearance_collector.lua"]:344: in function `?'
[string "@FrameXML/ChatFrame.lua"]:5224: in function <FrameXML/ChatFrame.lua:5170>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4888: in function <FrameXML/ChatFrame.lua:4887>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4924: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals:
bag = nil
slot = nil
(for index) = 0
(for limit) = 4
(for step) = 1
bag = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call upvalue 'GetContainerNumSlots' (a nil value)"
GetContainerNumSlots = nil
GetContainerItemLink = nil
S = <table> {
 ScanningTooltip = SezzUIScanningTooltip {
 }
 IsBeta = <function> defined @WardrobeTools/sUI.lua:49
 Scale = <function> defined @WardrobeTools/sUI.lua:109
 modules = <table> {
 }
 GetModule = <function> defined @WardrobeTools/sUI.lua:378
 SkinActionButton = <function> defined @WardrobeTools/sUI.lua:28
 myRealm = "Terenas"
 IsItemTradable = <function> defined @WardrobeTools/wardrobe/core.lua:353
 ItemIsValidTransmogrifySource = <function> defined @WardrobeTools/wardrobe/core.lua:245
 PlayerCanEquip = <function> defined @WardrobeTools/wardrobe/core.lua:282
 IsBagItemTradable = <function> defined @WardrobeTools/wardrobe/core.lua:344
 Clone = <function> defined @WardrobeTools/sUI.lua:517
 RegisterSlashCommand = <function> defined @WardrobeTools/sUI.lua:77
 UnregisterSlashCommand = <function> defined @WardrobeTools/sUI.lua:57
 UIParent = SezzUIParent {
 }
 CreateModule = <function> defined @WardrobeTools/sUI.lua:324
 myFactionGroup = "Alliance"
 myLevel = 60
 PlayerHasTransmog = <function> defined @WardrobeTools/wardrobe/core.lua:130
 GetModuleDefaultSettings = <function> defined @WardrobeTools/sUI.lua:370
 myName = "Manda"
 myClass = "WARRIOR"
 dummy = <function> defined @WardrobeTools/sUI.lua:28
}
select = <function> defined =[C]:-1
GetItemInfo = <function> defined =[C]:-1
LE_ITEM_CLASS_ARMOR = nil
LE_ITEM_CLASS_WEAPON = nil

**Comment by fubaWoW** [comment]
hopefully fixed all bugs now in this version here:
https://github.com/fubaWoW/WardrobeTools

PR is also out

**Comment by Uggers** [comment]
Nice one, thanks fuba!
