### ISSUE TITLE
Update for BFA 8.0

### ISSUE THREAD

**Issue by xajlox** [eTzmNcbkrng/WardrobeTools#2]
Is there anyone that can take a look at this addon to update for BFA is great addon that we shoud fix. Thanks you

**Comment by Uggers** [comment]
Hey just wanted to echo Xajlox's comment would be good if someone wouldn't mind taking a look. I did pm Sezz but looks like the forums had alot of posts removed

**Comment by ComaCanadian** [comment]
Well I don't know how to really use git, but I was able to fix the error with /ac and the boe equipping.

on line 162/163 you need to change GetNumEquipmentSets() to C_EquipmentSet.GetNumEquipmentSets() on both lines.. to look like this ..
```
local GetAppearanceCollectorEquipmentSetID = function()
	for i = 1, C_EquipmentSet.GetNumEquipmentSets() do
		local name, _, id = C_EquipmentSet.GetEquipmentSetInfo(i);
		if (name == equipmentSet) then
			return id;
		end
	end
end
```

after that it worked fine, though if you've just loaded into a character you have to wait a few seconds for it to 'scan' you bags of items for the equip scroll to work. 

I didn't have any other issues with mailing portion of the addon or anything else.

**Comment by ComaCanadian** [comment]
is the code in your file like: 
```
local`` GetAppearanceCollectorEquipmentSetID = function()
	for i = 1, C_EquipmentSet.GetNumEquipmentSets() do
		local name, _, id = C_EquipmentSet.GetEquipmentSetInfo(i);
		if (name == equipmentSet) then
			return id;
		end
	end
end
```

if so thats wrong, it needs to be like this on the fist line. notice the lack of `` 
`local GetAppearanceCollectorEquipmentSetID = function()`

if its already like that then I don't know, by the error the custom function on like 243 doesn't look to be anything out of the ordinary.. I only do lua as a hobby sorry.

**Comment by Uggers** [comment]
Na the ' was just github markdown gone wrong,

Do you mind zipping your version up so I can give it a try or at least compare in notepad the differences?

**Comment by ComaCanadian** [comment]
[WardrobeTools.zip](https://github.com/eTzmNcbkrng/WardrobeTools/files/2276335/WardrobeTools.zip)

**Comment by Uggers** [comment]
Many thanks that seemed to work,
No idea what was wrong with my version, I must have had a wierd , or `
somewhere

**Comment by ComaCanadian** [comment]
Also, seems if you have a character with no equipment sets already, it wont re-equip your gear/delete its temp set. To fix this open appearance_collector.lua on line 162, in the 'GetAppearanceCollectorEquipmentSetID' function from 
`for i = 1, C_EquipmentSet.GetNumEquipmentSets() do `
to
`for i = 0, C_EquipmentSet.GetNumEquipmentSets() do`

**Comment by penguinsane** [comment]
I just wanted to pop in and say thank you, ComaCanadian, you are amazing. This is one of the more obscure addons that I run and I ALWAYS miss it when it's broken.

**Comment by Hampen555** [comment]
Seems to be broken in 8.1 again, the equipping part still works with /ac but the mailing module doesn't seem to work, there is no mailing button.

**Comment by ComaCanadian** [comment]
Fix for 8.1 in the mailer.lua file

line 388
`PostalSelectOpenButton:SetPoint("TOPLEFT", "MailFramePortraitFrame", "RIGHT", 0, -2);`
you can either remove it completely or add two -- in front like
`--PostalSelectOpenButton:SetPoint("TOPLEFT", "MailFramePortraitFrame", "RIGHT", 0, -2);`

on like 410 (or 409 if you removed the previous line)
`sendButton:SetPoint("TOPLEFT", "MailFramePortraitFrame", "RIGHT", OpenMailReplyButton:GetWidth() * 1.5 + 4, -2);`
and remove the "PortraitFrame" to look like
`sendButton:SetPoint("TOPLEFT", "MailFrame", "RIGHT", OpenMailReplyButton:GetWidth() * 1.5 + 4, -2);`

**Comment by Uggers** [comment]
Thanks again ComaCanadian, you're a legend

**Comment by AvellaTheInsane** [comment]
@ComaCanadian instead of deleting things, just rename the "MailFramePortraitFrame" to "MailFramePortrait" in lines 388 and 410. That fixes it to look and function correctly even if you have Postal installed.

**Comment by ComaCanadian** [comment]
Thank you. I'm not super familiar with UI regions I tried to search for them but couldn't find anything specific. I only know a bit of LUA to get by fixing certain things, but there's a lot that goes over my head.

**Comment by AvellaTheInsane** [comment]
You are welcome. Truthfully, I don't know much about it myself, just enough to sometimes fix little things. Glad I could help  :)

**Comment by eTzmNcbkrng** [comment]
Thanks for these updates @ComaCanadian and @AvellaTheInsane, I have published them.
#5
