### ISSUE TITLE
White/Greys - Feature Request

### ISSUE THREAD

**Issue by Uggers** [eTzmNcbkrng/WardrobeTools#22]
Now that we can transmog whites/greys etc

Is it possible to make sure thats captured in the mailer and collector function?

**Comment by eTzmNcbkrng** [comment]
Yes, I've got that working but haven't pushed it yet. Very soon.

**Comment by eTzmNcbkrng** [comment]
031ca1b369f475d97a3ef261e4ee557b54778ad8 and 3b25e714ebda76367fa83f08c0de8ff0e970f5ac fix this.

**Comment by Uggers** [comment]
Thanks! Appreciate the continued support for this.
