### ISSUE TITLE
9.1 Issues

### ISSUE THREAD

**Issue by Uggers** [eTzmNcbkrng/WardrobeTools#9]
I am getting some issues with 9.1 as I think GetSlotTransmogSources has changed.

I attempted to fix this by changing to GetItemTransmogInfo but it does not seem to have worked fully.
If I type /ac it DOES open up the button now and let you equip items, however it doesn't close when it finishes, and the mail function isn't working.

Both appear to give this error, it might be caused by my attempted fix.

_9x WardrobeTools\wardrobe\core.lua:159: attempt to compare number with table
[string "@WardrobeTools\wardrobe\core.lua"]:159: in function 'PlayerHasTransmog'
[string "@WardrobeTools\wardrobe\appearance_collector.lua"]:48: in function <...dOns\WardrobeTools\wardrobe\appearance_collector.lua:42>
[string "@WardrobeTools\wardrobe\appearance_collector.lua"]:98: in function 'Update'
[string "@WardrobeTools\wardrobe\appearance_collector.lua"]:75: in function '?'
[string "@WardrobeTools\sUI.lua"]:181: in function <WardrobeTools\sUI.lua:179>

Locals:
item = "|cffa335ee|Hitem:187086::::::::60:73::14::1:28:709:::::|h[Deathsworn's Sterling Shoulderguards]|h|r"
checkSource = nil
forceRefresh = nil
isCollected = false
isCollectedSource = false
equipSlot = "INVTYPE_SHOULDER"
appearanceSourceID = <table> {
 Clear = <function> defined @FrameXML\ItemUtil.lua:199
 IsEqual = <function> defined @FrameXML\ItemUtil.lua:192
 Init = <function> defined @FrameXML\ItemUtil.lua:186
 illusionID = 0
 secondaryAppearanceID = 0
 appearanceID = 146531
}
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 3
(*temporary) = <table> {
 Clear = <function> defined @FrameXML\ItemUtil.lua:199
 IsEqual = <function> defined @FrameXML\ItemUtil.lua:192
 Init = <function> defined @FrameXML\ItemUtil.lua:186
 illusionID = 0
 secondaryAppearanceID = 0
 appearanceID = 146531
}
(*temporary) = 0
(*temporary) = <table> {
 Clear = <function> defined @FrameXML\ItemUtil.lua:199
 IsEqual = <function> defined @FrameXML\ItemUtil.lua:192
 Init = <function> defined @FrameXML\ItemUtil.lua:186
}
(*temporary) = "Init"
(*temporary) = "Init"
(*temporary) = <function> defined @FrameXML\ItemUtil.lua:186
(*temporary) = "Init"
(*temporary) = 4051731
(*temporary) = "attempt to compare number with table"
S = <table> {
 ScanningTooltip = SezzUIScanningTooltip {
 }
 GetModuleDefaultSettings = <function> defined @WardrobeTools\sUI.lua:369
 Scale = <function> defined @WardrobeTools\sUI.lua:108
 modules = <table> {
 }
 GetModule = <function> defined @WardrobeTools\sUI.lua:377
 SkinActionButton = <function> defined @WardrobeTools\sUI.lua:28
 myRealm = "Terenas"
 IsItemTradable = <function> defined @WardrobeTools\wardrobe\core.lua:330
 PlayerCanEquip = <function> defined @WardrobeTools\wardrobe\core.lua:259
 IsBagItemTradable = <function> defined @WardrobeTools\wardrobe\core.lua:321
 ItemIsValidTransmogrifySource = <function> defined @WardrobeTools\wardrobe\core.lua:226
 RegisterSlashCommand = <function> defined @WardrobeTools\sUI.lua:76
 UnregisterSlashCommand = <function> defined @WardrobeTools\sUI.lua:56
 UIParent = SezzUIParent {
 }
 CreateModule = <function> defined @WardrobeTools\sUI.lua:323
 Clone = <function> defined @WardrobeTools\sUI.lua:516
 myLevel = 60
 PlayerHasTransmog = <function> defined @WardrobeTools\wardrobe\core.lua:128
 IsBeta = <function> defined @WardrobeTools\sUI.lua:48
 myName = "Manda"
 myClass = "WARRIOR"
 dummy = <function> defined @WardrobeTools\sUI.lua:28
}
model = <unnamed> {
 0 = <userdata>
}
lastItem = "|cff1eff00|Hitem:186139::::::::60:73:::2:7453:1701:2:9:60:28:2043:::::|h[Mawsworn Javeliner's Targe of the Feverflare]|h|r"
lastResult = false
lastResultSource = false
select = <function> defined =[C]:-1
GetItemInfo = <function> defined =[C]:-1
equipSlotIDs = <table> {
 INVTYPE_RANGEDRIGHT = 16
 INVTYPE_SHIELD = 17
 INVTYPE_WEAPONOFFHAND = 17
 INVTYPE_RANGED = 16
 INVTYPE_WEAPON = 16
 INVTYPE_2HWEAPON = 16
 INVTYPE_WRIST = 9
 INVTYPE_NECK = 2
 INVTYPE_CLOAK = 15
 INVTYPE_BODY = 4
 INVTYPE_HEAD = 1
 INVTYPE_FEET = 8
 INVTYPE_HOLDABLE = 17
 INVTYPE_TABARD = -19
 INVTYPE_WEAPONMAINHAND = 16
 INVTYPE_HAND = 10
 INVTYPE_WAIST = 6
 INVTYPE_LEGS = 7
 INVTYPE_SHOULDER = 3
 INVTYPE_ROBE = 5
 INVTYPE_CHEST = 5
}
tonumber = <function> defined =[C]:-1
strmatch = <function> defined =[C]:-1
PlayerHasApperanceSource = <function> defined @WardrobeTools\wardrobe\core.lua:110_

**Comment by FindingArrow** [comment]
Same question. Have you fixed it?

**Comment by Uggers** [comment]
No, still can't nail down whats wrong, although I admit I haven't spent time on it since my ticket.

I'll try posting on the wowinterface to see if a dev can help, but probably not

**Comment by FindingArrow** [comment]
local transmogInfo = model:GetItemTransmogInfo(equipSlotIDs[equipSlot])
			local appearanceSourceID = nil
			if transmogInfo and 
				transmogInfo.appearanceID ~= nil and
				transmogInfo.appearanceID ~= 0 then
				appearanceSourceID = transmogInfo.appearanceID
			end

**Comment by Uggers** [comment]
did you fix it? or just an excerpt you found?

**Comment by FindingArrow** [comment]
it works well. Have a try,

**Comment by Uggers** [comment]
sorry, where did you add this? I updated the core to be like this 

[core.txt](https://github.com/eTzmNcbkrng/WardrobeTools/files/6925738/core.txt)

But not sure where you've added the above? Can you share your version ?

Thanks for the assistance though

**Comment by FindingArrow** [comment]
local PlayerHasTransmog = function(item, checkSource, forceRefresh)
	if (not item or (checkSource and not S.ItemIsValidTransmogrifySource(item))) then return; end
	model:SetUnit("player");
	model:Undress();

	if (not forceRefresh and lastItem and lastItem == item) then
		-- Tooltip update, reuse last results
		return lastResult, lastResultSource;
	end

	local isCollected, isCollectedSource = false, false;
	local equipSlot = select(9, GetItemInfo(item));

--	S:Debug("Item: "..item, "Core");
--	S:Debug("equipSlot: "..(equipSlot ~= nil and equipSlot or "Unknown"), "Core");
	if (equipSlot and equipSlot ~= "") then
		if (equipSlotIDs[equipSlot] < 0) then
			-- Workaround for tabards
			local itemID = type(item) == "string" and tonumber(strmatch(item, "item:(%d+)")) or item;
			isCollected = C_TransmogCollection.PlayerHasTransmog(itemID);
		else
			model:TryOn(item);

			local transmogInfo = model:GetItemTransmogInfo(equipSlotIDs[equipSlot])
			local appearanceSourceID = nil
			if transmogInfo and 
				transmogInfo.appearanceID ~= nil and
				transmogInfo.appearanceID ~= 0 then
				appearanceSourceID = transmogInfo.appearanceID
			end

--			S:Debug("Appearance Source ID: "..(appearanceSourceID ~= nil and appearanceSourceID or "Unknown"), "Core");
			if (appearanceSourceID and appearanceSourceID > 0) then
				-- TODO:
				-- C_TransmogCollection.GetAppearanceInfoBySource(appearanceSourceID)
				-- Returns .appearanceIsCollected/.sourceIsCollected but doesn't return anything if player
				-- cannot use the item...
--				S:Dump(C_TransmogCollection.GetAppearanceSourceInfo(appearanceSourceID));
--				S:Dump(C_TransmogCollection.GetAppearanceInfoBySource(appearanceSourceID));

				local appearanceInfo = C_TransmogCollection.GetAppearanceInfoBySource(appearanceSourceID);
--				S:Debug("Appearance Info: "..(appearanceInfo ~= nil and "OK" or "nil"), "Core");
				if (appearanceInfo) then
					-- This is the data we want, but we can only use it if the player can equip the item.
					isCollected = appearanceInfo.appearanceIsCollected or appearanceInfo.sourceIsCollected; -- Buggy sometimes
					isCollectedSource = appearanceInfo.sourceIsCollected;
				else
					-- Failover #1
					isCollected = C_TransmogCollection.PlayerHasTransmogItemModifiedAppearance(appearanceSourceID);
					isCollectedSource = isCollected;
--					S:Debug("PlayerHasTransmogItemModifiedAppearance: "..(isCollected and "Yes" or "No"), "Core");

					if (not isCollected) then
					-- Failover #2
						local _, appearanceID = C_TransmogCollection.GetAppearanceSourceInfo(appearanceSourceID);
--						S:Debug("Appearance ID: "..(appearanceID ~= nil and appearanceID or "Unknown"), "Core");
						if (appearanceID) then
							local appearanceSources = C_TransmogCollection.GetAppearanceSources(appearanceID)
--							S:Debug("Appearance Sources: "..(appearanceSources and #appearanceSources or 0), "Core");
							if (appearanceSources) then
								for _, appearanceSource in pairs(appearanceSources) do
--									S:Debug("Source.isCollected: "..(appearanceSource.isCollected and "Yes" or "No"), "Core");
									if (appearanceSource.isCollected) then
--										print("C_TransmogCollection.GetAppearanceSourceInfo");
										isCollected = true;
										break;
									end
								end
							end
						else
							-- Failover #3, doesn't show if already collected any other items with the same appearance.
							isCollected = select(5, C_TransmogCollection.GetAppearanceSourceInfo(appearanceSourceID)) or false;
							if (not isCollected and C_TransmogCollection.GetShowMissingSourceInItemTooltips()) then
								isCollected = PlayerHasApperanceSource(item);
--								if (isCollected) then
--									S:Debug("PlayerHasApperanceSourceTooltip!");
--								end
							end
						end
					end
				end
			end

			model:Undress();
		end
	end

	-- Cache results
	lastItem = item;
	lastResult = isCollected;
	lastResultSource = isCollectedSource;

	return isCollected, isCollectedSource;
end

this function.

**Comment by FindingArrow** [comment]
[core.txt](https://github.com/eTzmNcbkrng/WardrobeTools/files/6925782/core.txt)

**Comment by eTzmNcbkrng** [comment]
@Uggers Is this you? - https://web.archive.org/web/20180621125916/http://stormspire.net/general-tradeskillmaster-discussion/18409-mailing-groups-boe-armor-classes.html

**Comment by Uggers** [comment]
> @Uggers Is this you? - https://web.archive.org/web/20180621125916/http://stormspire.net/general-tradeskillmaster-discussion/18409-mailing-groups-boe-armor-classes.html

Yup thats me.. Sorry something wrong?

**Comment by eTzmNcbkrng** [comment]
No, not at all, I just noticed that the link I put in the ReadMe doesn't work so was using Wayback Machine to find the old post and was thinking the name Uggers looked very familiar and realised I saw it in this issue an hour or so before searching for an archive.

You've been around this addon for a while lol.

**Comment by Uggers** [comment]
Ahhh, yeah, 
Only addon that does this, makes life very easy farming old BoE Transmogs.

 Tyrsenus managed to fix it recently, (although I still have issues with the temporary "Sezz" armor set not  being removed on some chars and re-equping the normal armor once you've gone through it,
But only happens on some chars not all so no idea.

But yeah, its cool addon even after stormspire went lol

**Comment by eTzmNcbkrng** [comment]
I've stopped playing wow on Retail servers, might return for Wrath Classic, so not using this addon anymore. I merged all of @Tyrsenus' updates, maybe he'll look at the issue you're having?

**Comment by Uggers** [comment]
Yeah he did say he'd look but hasn't had chance yet, (spoke to him Via Reddit)
But its alright, I realize I'm probably one of very few using it so I'm not going to complain if no one wants to take a look.

At some point it'll probably stop working entirely so i'll have to figure it out some other way
